"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
const setores=[
{setor:13,dias:"Segunda, quarta e sexta",periodo:"Diurno — a partir das 7h",bairros:["Condomínio Bela Vitta","Jardim Dona Regina Picelli","Conjunto Habitacional Boa Esperança","Jardim Santa Clara","Jardim Floridiana","Jardim América","Santa Clara II","Jardim São Caetano 2","Residencial Graciole"]},
{setor:9,dias:"Segunda, quarta e sexta",periodo:"Diurno — a partir das 7h",bairros:["Condomínio Clube Home","Conjunto Habitacional RC4","Jardim M. Maniero","Jardim Santa Elisa","Jardim Figueira","Jardim Paulista 2","Jardim das Paineiras","Jardim Panorama","Condomínio Alto do Bosque","Conjunto Habitacional Rio Claro E","Granja Regina","Assentamento Betel"]},
{setor:14,dias:"Segunda, quarta e sexta",periodo:"Diurno — a partir das 7h",bairros:["Parque Mãe Preta","Vila Industrial","Chácara Rupiara","Recreio das Águas Claras","Sítio Santa Elisabete","Residencial Florença","Conjunto residencial Vila Verde","Vila Cristina (baxadão)"]},
{setor:16,dias:"Segunda, quarta e sexta",periodo:"Diurno — a partir das 7h",bairros:["Jardim Santa Maria","Residencial das Flores","Jardim Progresso 1 e 2","Parque São Jorge","Residencial dos Bosques de Rio Claro","Jardim Azul","Jardim São João","Jardim São Caetano","São Jorge"]},
{setor:18,dias:"Segunda, quarta e sexta",periodo:"Diurno — a partir das 7h",bairros:["Recando Paraíso","Jardim Santa Maria (rua 16 a rua jacutinga)","Jardim Boa Vista 1 e 2","Recanto Verde 1","Recanto Verde 2","Jardim Fazendinha","Itapé","Ferraz","Distrito Ajapi","Vila Nova Ajapi","Jardim Monte Alegre","Jardim Terras de Ajapi","Nova Ajapi","Vila Di Napoli","Alam Grei","Mata Negra (só seg e sex)","Estrada do Sobrado (só seg e sex)"]},
{setor:20,dias:"Segunda, quarta e sexta",periodo:"Diurno — a partir das 7h",bairros:["Conjunto Habitacional Arco-Íris","Chácara Bela Vista","Distrito Industrial","Parque Industrial Margarete","Industrial Expresso","Parque dos Eucalíptos","Cidade Azul 2","Jardim Parque Industrial","Parque das Árvores","Residencial Primavera","Jardim Village","Vila São Miguel","Vila Cristina"]},
{setor:8,dias:"Terça, quinta e sábado",periodo:"Diurno — a partir das 7h",bairros:["Jardim Araucária","Jardim Cidade Azul","Jardim Olinda","Vila BNH","Parque Universitário","Jardim Wenzel avenida 44 e 42","Vila Santa Terezinha"]},
{setor:10,dias:"Terça, quinta e sábado",periodo:"Diurno — a partir das 7h",bairros:["Condomínio Residencial Califórnia","Condomínio Petit Village","Condomínio Residencial Colorado","Condomínio Residencial Vista Verde","Condomínio Residencial Portal do Sol","Jardim Brasília II","Jardim Nova Rio Claro","Diário Ville","Jardim das palmeiras (rua2 a rua 9)","Condomínio San Marino","Condomínio Vista Alegre"]},
{setor:12,dias:"Terça, quinta e sábado",periodo:"Diurno — a partir das 7h",bairros:["Jardim Cherveson","Jardim Independência","Parque das Indústrias","Jardim Hipódromo","Jardim Ipanema"]},
{setor:15,dias:"Terça, quinta e sábado",periodo:"Diurno — a partir das 7h",bairros:["Jardim Esmeralda","Condomínio Residencial Palmeiras 1 e 2","Park Palmeira","Guanabara I e II","Jardim Novo 2","Jardim das palmeiras (rua10 a rua 16)"]},
{setor:17,dias:"Terça, quinta e sábado",periodo:"Diurno — a partir das 7h",bairros:["Distrito Assistência","Assistência de Baixo","Campo Belo","Residencial Parada das Pedras","Recanto das Pedras","Industrial Cidade Azul","Condomínio Industrial","Condomínio Residencial Jardim Europa","Residencial Campestre Vila Rica","Jardim Novo I","Residencial Vila Rosa","Jardim Parque das Nações","Terra Nova"]},
{setor:19,dias:"Terça, quinta e sábado",periodo:"Diurno — a partir das 7h",bairros:["Batovi","Residencial Benjamim de Castro","Jardim Paulista","Vila Anhanguera","Veneza","Jardim Centenário","Jardim Maria Cristina","Loteamento Sebastião dos Santos Lima","Jardim Bom Sucesso","Novo Jardim Wenzel","Bom Retiro 1 e 2"]},
{setor:3,dias:"Segunda, quarta e sexta",periodo:"Noturno — a partir das 17h",bairros:["Jardim Itapuã","Jardim Kennedy","Jardim Anhanguera","Jardim Donangela","Cidade Jardim","Bairro do Estádio","Condomínio Resindencial Jardim Botânico","Condomínio Residencial Manacás","Condomínio Di Scarpa","Condomínio Residencial Villagio Urca","Condomínio Villagio Gavea","Condomínio Residencial Ilha Imperial","Vila Paulina","Condomínio Cidade Jardim","Condomínio Ville Di Scarpa","Jardim Leblon","Jardim Porto Fino","Condomínio Villagio Ipanema","Jardim Residencial Copacabana"]},
{setor:4,dias:"Segunda, quarta e sexta",periodo:"Noturno — a partir das 17h",bairros:["Condomínio Residencial Portal Copacabana","Vila Santo Antônio","Anexo Cidade Jardim","Vila Horto Florestal","Condomínio Veredas","Condomínio Residencial Jardins de Floresta 1","Vila Paulista","Jardim Conduta","Vila do Horto","Jardim do Horto","Jardim Residencial Bianchini","Condomínio Residencial Villagio do Coop","Parque Flórida"]},
{setor:5,dias:"Segunda, quarta e sexta",periodo:"Noturno — a partir das 17h",bairros:["Vila Alemã","Jardim do Ipê","Desmembramento Tingu","Vila Nova","Vila São José","Jardim Bandeirante","Vila Aparecida"]},
{setor:7,dias:"Segunda, quarta e sexta",periodo:"Noturno — a partir das 17h",bairros:["Vila Martins","Vila Saibreiro","Jardim Portugal","Jardim Primavera","Vila Operária","Jardim Alfredo Karan","Jardim Alto do Santana","Vila Santa Filomena"]},
{setor:1,dias:"Terça, quinta e sábado",periodo:"Noturno — a partir das 17h",bairros:["Vila Ribeiro","Bairro Santa Cruz","Vila do Rádio","Santana"]},
{setor:2,dias:"Terça, quinta e sábado",periodo:"Noturno — a partir das 17h",bairros:["Cidade Claret","Condomínio Chácara Claret","Cidade Claret 2","Jardim Mirassol","Jardim São Paulo 2","Jardim São Paulo","Jardim Shangrilá","Jardim Bela Vista"]},
{setor:6,dias:"Terça, quinta e sábado",periodo:"Noturno — a partir das 17h",bairros:["UNESP","Bela Vista","Vila Bela Vista","Jardim Nossa Senhora da Saúde I","Jardim Nossa Senhora da Saúde II","Vila Indaiá","Cidade Nova","Jardim Vila Bela"]},
{setor:11,dias:"Terça, quinta e sábado",periodo:"Noturno — a partir das 17h",bairros:["Consolação","Jardim do Trevo","Jardim Quitandinha","Bairro Olímpico","Jardim Valéria","Jardim Rio Claro","Jardim Inocoop","Chácara Luza","Residencial Quebec","Residencial Vila Verde II"]},
{setor:21,dias:"Diário",periodo:"Noturno — a partir das 17h",bairros:["Zona Central","Bairro de Saúde","Bairro São Benedito","Bairro Boa Morte"]}
];
const norm=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
export default function Page(){const[busca,setBusca]=useState("");const destaque=setores[0];const resultados=useMemo(()=>{const q=norm(busca);return q?setores.flatMap(s=>s.bairros.filter(b=>norm(b).includes(q)).map(b=>({bairro:b,...s}))):[]},[busca]);return <main className="min-h-screen bg-slate-100 pb-12"><header className="bg-emerald-800 p-5 text-white"><div className="mx-auto max-w-md"><Link href="/utilidades" className="text-xs font-bold">← Telefones e Serviços</Link><div className="mt-3 text-center text-4xl">🗑️</div><h1 className="text-center text-2xl font-black">Coleta de Lixo</h1><p className="text-center text-xs">Consulte os dias da coleta pelo bairro</p></div></header><div className="mx-auto max-w-md space-y-4 p-4"><section className="rounded-3xl bg-white p-4 shadow"><b className="text-sm">🔎 Digite seu bairro</b><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Ex.: Jardim Floridiana" className="mt-2 w-full rounded-2xl border p-3"/>{busca&&<div className="mt-3 space-y-2">{resultados.length?resultados.map((r,i)=><div key={r.bairro+i} className="rounded-xl bg-emerald-50 p-3"><b>{r.bairro}</b><p className="text-xs font-bold text-emerald-800">Setor {r.setor} • {r.dias}</p><p className="text-xs">{r.periodo}</p></div>):<p className="text-xs text-slate-500">Nenhum bairro encontrado.</p>}</div>}</section>{!busca&&<section className="rounded-3xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-black text-amber-700">NOSSA REGIÃO</p><h2 className="text-xl font-black">Setor 13</h2><p className="text-sm font-bold">📅 {destaque.dias}</p><p className="text-xs">🕒 {destaque.periodo}</p><div className="mt-3 flex flex-wrap gap-2">{destaque.bairros.map(b=><span key={b} className="rounded-xl bg-white px-2 py-1 text-[11px] font-bold">{b}</span>)}</div></section>}<details className="rounded-3xl bg-white p-4 shadow"><summary className="cursor-pointer text-sm font-black">📋 Ver todos os setores e bairros</summary><div className="mt-3 space-y-3">{[...setores].sort((a,b)=>a.setor-b.setor).map(s=><div key={s.setor} className="rounded-xl bg-slate-50 p-3"><b>Setor {s.setor}</b><p className="text-xs font-bold text-emerald-700">{s.dias}</p><p className="text-xs">{s.periodo}</p><p className="mt-1 text-xs">{s.bairros.join(" • ")}</p></div>)}</div></details></div></main>}
