"use client";
import { useEffect, useMemo, useState } from "react";

type Alerta={id:string;titulo:string;severidade:string;severidadeNivel:number;inicio:string|null;fim:string|null;descricao:string;instrucao:string;fonte:string};
type Clima={atualizadoEm:string;current:Record<string,number|string>;hourly:Record<string,Array<number|string>>;daily:Record<string,Array<number|string>>};

function condicao(c:number,dia=true):[string,string]{
 if(c===0)return[dia?"Ensolarado":"Céu limpo",dia?"☀️":"🌙"];
 if(c===1)return["Poucas nuvens",dia?"🌤️":"🌙"]; if(c===2)return["Parcialmente nublado","⛅"]; if(c===3)return["Nublado","☁️"];
 if([45,48].includes(c))return["Neblina","🌫️"]; if([51,53,55,56,57].includes(c))return["Garoa","🌦️"];
 if([61,63,65,66,67].includes(c))return[c>=65?"Chuva forte":"Chuva","🌧️"]; if([80,81,82].includes(c))return[c===82?"Pancadas fortes":"Pancadas de chuva","🌦️"];
 if([95,96,97,99].includes(c))return["Tempestade","⛈️"]; return["Tempo variável","🌤️"];
}
const num=(v:unknown,c=0)=>{const n=Number(v);return Number.isFinite(n)?n.toFixed(c).replace(".",","):"--"};
const hora=(v:string)=>v?.slice(11,16)||"--:--";
function diaNome(v:string,i:number){if(i===0)return"Hoje";if(i===1)return"Amanhã";return new Date(v+"T12:00:00").toLocaleDateString("pt-BR",{weekday:"short"}).replace(".","")}
function direcao(g:number){const p=["N","NE","L","SE","S","SO","O","NO"];return p[Math.round((((g%360)+360)%360)/45)%8]}

export default function ClimaPage(){
 const[clima,setClima]=useState<Clima|null>(null);const[alertas,setAlertas]=useState<Alerta[]>([]);const[erro,setErro]=useState("");const[aberto,setAberto]=useState<Alerta|null>(null);
 useEffect(()=>{(async()=>{try{const[c,a]=await Promise.all([fetch("/api/clima"),fetch("/api/alertas",{cache:"no-store"})]);if(!c.ok)throw new Error();setClima(await c.json());if(a.ok){const x=await a.json();if(Array.isArray(x.alertas))setAlertas(x.alertas)}}catch{setErro("Não foi possível atualizar a previsão agora.")}})()},[]);
 const horas=useMemo(()=>{if(!clima)return[];const t=clima.hourly.time as string[];const agora=String(clima.current.time||"");let n=t.findIndex(x=>x>=agora.slice(0,13)+":00");if(n<0)n=0;return t.slice(n,n+12).map((x,j)=>({i:n+j,t:x}))},[clima]);
 if(!clima)return <main className="min-h-screen bg-slate-100 px-4 py-8"><div className="mx-auto max-w-6xl rounded-3xl bg-white p-8 text-center font-bold text-slate-600">{erro||"🌦️ Atualizando o clima de Rio Claro..."}</div></main>;
 const c=clima.current,h=clima.hourly,d=clima.daily;const[texto,icone]=condicao(Number(c.weather_code),Number(c.is_day)===1);const alerta=alertas[0];
 return <main className="min-h-screen bg-gradient-to-b from-sky-100 via-slate-50 to-white px-3 py-4 pb-28 sm:px-5"><div className="mx-auto max-w-6xl space-y-4">
  <section className="overflow-hidden rounded-[28px] bg-gradient-to-br from-blue-950 via-blue-800 to-sky-600 p-5 text-white shadow-xl sm:p-7">
   <div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-sky-200">Sobradão 360 • Clima</p><h1 className="mt-1 text-2xl font-black">Rio Claro, SP</h1><p className="mt-1 text-xs text-blue-100">Previsão local • atualização automática</p></div><span className="text-5xl">{icone}</span></div>
   <div className="mt-6 flex items-end gap-4"><div className="text-6xl font-black tracking-tighter">{num(c.temperature_2m)}°</div><div className="pb-2"><p className="text-lg font-black">{texto}</p><p className="text-xs text-blue-100">Sensação de {num(c.apparent_temperature)}°C</p></div></div>
   <div className="mt-5 grid grid-cols-3 gap-2 border-t border-white/20 pt-4 text-center"><div><p className="text-[9px] uppercase text-blue-200">Máxima</p><b>{num(d.temperature_2m_max?.[0])}°</b></div><div><p className="text-[9px] uppercase text-blue-200">Mínima</p><b>{num(d.temperature_2m_min?.[0])}°</b></div><div><p className="text-[9px] uppercase text-blue-200">Chuva</p><b>{num(d.precipitation_probability_max?.[0])}%</b></div></div>
  </section>
  {alerta&&<button onClick={()=>setAberto(alerta)} className={`w-full rounded-2xl border p-4 text-left shadow-sm ${alerta.severidadeNivel>=2?"border-orange-200 bg-orange-50 text-orange-950":"border-yellow-200 bg-yellow-50 text-yellow-950"}`}><div className="flex items-center gap-3"><span className="text-2xl">⚠️</span><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase">Alerta oficial INMET • Rio Claro</p><p className="truncate text-sm font-black">{alerta.titulo} · {alerta.severidade}</p></div><span className="text-xs font-black">VER ›</span></div></button>}
  <section className="rounded-3xl bg-white p-4 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black text-slate-900">Próximas horas</h2><p className="text-[10px] text-slate-400">Temperatura e chance de chuva</p></div><span className="text-xl">🕐</span></div><div className="flex gap-2 overflow-x-auto pb-2">{horas.map(({i,t},j)=>{const[,ic]=condicao(Number(h.weather_code?.[i]));return <div key={t} className={`min-w-[76px] rounded-2xl p-3 text-center ${j===0?"bg-blue-900 text-white":"bg-slate-50 text-slate-800"}`}><p className="text-[10px] font-bold">{j===0?"Agora":hora(t)}</p><div className="my-2 text-2xl">{ic}</div><p className="text-lg font-black">{num(h.temperature_2m?.[i])}°</p><p className={`mt-1 text-[10px] font-black ${j===0?"text-sky-200":"text-blue-600"}`}>💧 {num(h.precipitation_probability?.[i])}%</p></div>})}</div></section>
  <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["💧","Umidade",num(c.relative_humidity_2m)+"%"],["💨","Vento",num(c.wind_speed_10m)+" km/h "+direcao(Number(c.wind_direction_10m))],["🌬️","Rajadas",num(c.wind_gusts_10m)+" km/h"],["🔵","Pressão",num(c.pressure_msl)+" hPa"],["☁️","Nuvens",num(c.cloud_cover)+"%"],["🌧️","Chuva agora",num(c.precipitation,1)+" mm"],["🌅","Nascer do sol",hora(String(d.sunrise?.[0]))],["🌇","Pôr do sol",hora(String(d.sunset?.[0]))]].map(([ic,l,v])=><div key={l} className="rounded-2xl bg-white p-4 shadow-sm"><span className="text-xl">{ic}</span><p className="mt-2 text-[9px] font-black uppercase text-slate-400">{l}</p><p className="mt-1 text-sm font-black text-slate-800">{v}</p></div>)}</section>
  <section className="rounded-3xl bg-white p-4 shadow-sm"><h2 className="font-black text-slate-900">🌧️ Chuva hoje</h2><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-blue-50 p-3"><p className="text-[9px] font-black uppercase text-blue-500">Chance</p><b className="text-xl text-blue-900">{num(d.precipitation_probability_max?.[0])}%</b></div><div className="rounded-2xl bg-blue-50 p-3"><p className="text-[9px] font-black uppercase text-blue-500">Acumulado</p><b className="text-xl text-blue-900">{num(d.precipitation_sum?.[0],1)} mm</b></div><div className="rounded-2xl bg-blue-50 p-3"><p className="text-[9px] font-black uppercase text-blue-500">UV máx.</p><b className="text-xl text-blue-900">{num(d.uv_index_max?.[0],1)}</b></div></div></section>
  <section className="rounded-3xl bg-white p-4 shadow-sm"><h2 className="mb-3 font-black text-slate-900">Previsão para 7 dias</h2><div className="divide-y divide-slate-100">{(d.time||[]).slice(0,7).map((v,i)=>{const[tx,ic]=condicao(Number(d.weather_code?.[i]));return <div key={String(v)} className="grid grid-cols-[72px_1fr_auto] items-center gap-2 py-3"><div><p className="text-xs font-black capitalize">{diaNome(String(v),i)}</p><p className="text-[9px] text-slate-400">{String(v).slice(8,10)}/{String(v).slice(5,7)}</p></div><div className="flex items-center gap-2"><span className="text-2xl">{ic}</span><div><p className="text-xs font-bold text-slate-700">{tx}</p><p className="text-[10px] font-bold text-blue-600">💧 {num(d.precipitation_probability_max?.[i])}% · {num(d.precipitation_sum?.[i],1)} mm</p></div></div><div className="text-right text-sm"><b>{num(d.temperature_2m_max?.[i])}°</b><span className="ml-2 text-slate-400">{num(d.temperature_2m_min?.[i])}°</span></div></div>})}</div></section>
  <p className="px-2 text-center text-[9px] leading-4 text-slate-400">Previsão: Open-Meteo • Alertas oficiais: INMET. Dados meteorológicos são estimativas e podem mudar.</p>
 </div>
 {aberto&&<div onClick={()=>setAberto(null)} className="fixed inset-0 z-[110] flex items-center justify-center bg-black/50 p-4"><div onClick={e=>e.stopPropagation()} className="max-h-[80vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl"><div className="flex justify-between gap-3"><div><p className="text-[10px] font-black uppercase text-orange-600">⚠️ Alerta oficial INMET</p><h2 className="mt-1 text-xl font-black">{aberto.titulo}</h2><p className="text-sm font-bold text-orange-700">{aberto.severidade}</p></div><button onClick={()=>setAberto(null)} className="h-9 w-9 rounded-full bg-slate-100 font-black">×</button></div>{aberto.inicio&&<p className="mt-4 text-xs"><b>Início:</b> {new Date(aberto.inicio).toLocaleString("pt-BR")}</p>}{aberto.fim&&<p className="mt-2 text-xs"><b>Término:</b> {new Date(aberto.fim).toLocaleString("pt-BR")}</p>}{aberto.descricao&&<p className="mt-4 whitespace-pre-line text-sm leading-6 text-slate-600">{aberto.descricao}</p>}{aberto.instrucao&&<div className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm text-slate-700"><b>🛡️ Recomendações</b><p className="mt-1 whitespace-pre-line">{aberto.instrucao}</p></div>}</div></div>}
 </main>
}
