import { NextResponse } from "next/server";

export async function GET() {
  try {
    const telefonesUteis = [
      { id: "1", titulo: "Polícia Militar", categoria: "Emergência", telefone: "190", horario: "24h", icone: "🚨" },
      { id: "2", titulo: "SAMU", categoria: "Emergência médica", telefone: "192", horario: "24h", icone: "🚑" },
      { id: "3", titulo: "Corpo de Bombeiros", categoria: "Emergência", telefone: "193", horario: "24h", icone: "🚒" },
      { id: "4", titulo: "Defesa Civil", categoria: "Emergência", telefone: "199", horario: "24h", icone: "⚠️" },
      { id: "5", titulo: "Guarda Civil Municipal", categoria: "Segurança", telefone: "153", horario: "24h", icone: "🛡️" },
      { id: "6", titulo: "Disque Direitos Humanos", categoria: "Direitos humanos", telefone: "100", horario: "24h", icone: "👥" },
      { id: "7", titulo: "Central da Mulher", categoria: "Violência contra a mulher", telefone: "180", horario: "24h", icone: "🟣" },
      { id: "8", titulo: "Prefeitura de Rio Claro", categoria: "Prefeitura", telefone: "(19) 3526-7100", horario: "Comercial", icone: "🏛️" },
      { id: "9", titulo: "Ouvidoria Municipal", categoria: "Reclamações/solicitações", telefone: "156 / (19) 3526-7145", horario: "Comercial", icone: "📢" },
      { id: "10", titulo: "Serviços Públicos", categoria: "Manutenção urbana", telefone: "(19) 3527-2763", horario: "Comercial", icone: "🔧" },
      { id: "11", titulo: "Iluminação Pública", categoria: "Poste/lâmpada", telefone: "(19) 3526-7127", horario: "Comercial", icone: "💡" },
      { id: "12", titulo: "Iluminação Pública WhatsApp", categoria: "Iluminação", telefone: "(19) 99495-9124", horario: "—", icone: "💬" },
      { id: "13", titulo: "Secretaria de Obras", categoria: "Obras públicas", telefone: "(19) 3522-1979", horario: "Comercial", icone: "🏗️" },
      { id: "14", titulo: "Mobilidade Urbana", categoria: "Trânsito", telefone: "(19) 3522-1919", horario: "Comercial", icone: "🚦" },
      { id: "15", titulo: "Departamento de Transporte", categoria: "Transporte", telefone: "(19) 3522-1990", horario: "Comercial", icone: "🚌" },
      { id: "16", titulo: "Departamento de Trânsito", categoria: "Trânsito/sinalização", telefone: "(19) 3522-1902", horario: "Comercial", icone: "🛑" },
      { id: "17", titulo: "Meio Ambiente", categoria: "Meio ambiente", telefone: "(19) 3522-1997", horario: "Comercial", icone: "🌿" },
      { id: "18", titulo: "Resíduos Sólidos", categoria: "Lixo/resíduos", telefone: "(19) 3522-2944", horario: "Comercial", icone: "🗑️" },
      { id: "19", titulo: "Proteção Animal / Canil", categoria: "Animais", telefone: "(19) 3532-4115", horario: "Comercial", icone: "🐶" },
      { id: "20", titulo: "Zonoses / CCZ", categoria: "Zoonoses", telefone: "(19) 3522-1435", horario: "Comercial", icone: "🐾" },
      { id: "21", titulo: "Procon Centro", categoria: "Defesa do consumidor", telefone: "(19) 3533-1944", horario: "Comercial", icone: "⚖️" },
      { id: "22", titulo: "Procon Chervezon", categoria: "Defesa do consumidor", telefone: "(19) 3523-5985", horario: "Comercial", icone: "⚖️" },
      { id: "23", titulo: "Pessoa com Deficiência", categoria: "Inclusão", telefone: "(19) 3526-7138", horario: "Comercial", icone: "♿" },
      { id: "24", titulo: "Desenvolvimento Social", categoria: "Assistência social", telefone: "(19) 3522-1930", horario: "Comercial", icone: "🤝" },
      { id: "25", titulo: "DAAE – Água", categoria: "Água", telefone: "0800 019 0505", horario: "24h", icone: "💧" },
      { id: "26", titulo: "DAAE – Esgoto", categoria: "Esgoto", telefone: "0800 771 0001", horario: "—", icone: "🚰" },
      { id: "27", titulo: "Neoenergia Elektro", categoria: "Energia elétrica", telefone: "0800 701 0102", horario: "24h", icone: "⚡" },
      { id: "28", titulo: "Neoenergia Elektro WhatsApp", categoria: "Energia", telefone: "(19) 2122-1696", horario: "—", icone: "💬" },
      { id: "29", titulo: "Claro Residencial", categoria: "Internet/TV/telefone", telefone: "10621", horario: "—", icone: "📺" },
      { id: "30", titulo: "Claro Móvel", categoria: "Celular", telefone: "1052", horario: "—", icone: "📱" },
      { id: "31", titulo: "TIM", categoria: "Celular", telefone: "*1056 / 144", horario: "—", icone: "📱" },
      { id: "32", titulo: "TIM UltraFibra", categoria: "Internet", telefone: "10341", horario: "—", icone: "🌐" },
      { id: "33", titulo: "Vivo", categoria: "Telefonia/internet", telefone: "10315 / 1058", horario: "—", icone: "📱" },
      { id: "34", titulo: "Algar Telecom", categoria: "Telefonia/internet", telefone: "10312", horario: "24h", icone: "☎️" },
      { id: "35", titulo: "Anatel", categoria: "Reclamação de operadoras", telefone: "1331", horario: "—", icone: "📋" },
      { id: "36", titulo: "Desktop Internet", categoria: "Internet", telefone: "0800 731 3100", horario: "—", icone: "💻" },
      { id: "37", titulo: "Fundação Municipal de Saúde", categoria: "Saúde", telefone: "(19) 3522-3600", horario: "Comercial", icone: "🏥" },
      { id: "38", titulo: "UPA Bairro do Estádio", categoria: "Urgência", telefone: "(19) 3522-1818", horario: "24h", icone: "🏥" },
      { id: "39", titulo: "UPA Chervezon", categoria: "Urgência", telefone: "(19) 3533-7272", horario: "24h", icone: "🏥" },
      { id: "40", titulo: "PA Nossa Senhora de Lourdes", categoria: "Urgência", telefone: "(19) 3533-5484", horario: "24h", icone: "🏥" },
      { id: "41", titulo: "Pronto-Socorro Ginecológico/Obstetrícia", categoria: "Saúde", telefone: "(19) 3535-7002", horario: "24h", icone: "🩺" },
      { id: "42", titulo: "CAPS III 18 de Maio", categoria: "Saúde mental", telefone: "(19) 3536-3365", horario: "24h", icone: "🧠" },
      { id: "43", titulo: "Santa Casa", categoria: "Hospital", telefone: "(19) 3535-7000", horario: "—", icone: "🏨" },
      { id: "44", titulo: "Hospital São Rafael", categoria: "Hospital/Maternidade", telefone: "(19) 3535-7050", horario: "—", icone: "🏨" },
      { id: "45", titulo: "Hospital Unimed I", categoria: "Hospital", telefone: "(19) 3522-7000", horario: "—", icone: "🏥" },
      { id: "46", titulo: "Hospital Unimed II – Evangélico", categoria: "Hospital", telefone: "(19) 3524-2205", horario: "—", icone: "🏥" },
      { id: "47", titulo: "Santa Filomena", categoria: "Hospital/Maternidade", telefone: "(19) 2111-4500", horario: "—", icone: "🏨" },
      { id: "48", titulo: "Bezerra de Menezes", categoria: "Saúde mental", telefone: "(19) 3524-2700", horario: "—", icone: "🧠" },
      { id: "49", titulo: "UBS Jardim Chervezon", categoria: "UBS", telefone: "(19) 3534-5195", horario: "—", icone: "🏥" },
      { id: "50", titulo: "UBS 29", categoria: "UBS", telefone: "(19) 3524-9577", horario: "—", icone: "🏥" },
      { id: "51", titulo: "UBS Wenzel", categoria: "UBS", telefone: "(19) 3533-3343", horario: "—", icone: "🏥" },
      { id: "52", titulo: "UBS Vila Cristina", categoria: "UBS", telefone: "(19) 3527-2908", horario: "—", icone: "🏥" },
      { id: "53", titulo: "USF Nosso Teto/Boa Vista", categoria: "USF", telefone: "(19) 3533-3522", horario: "—", icone: "🏥" },
      { id: "54", titulo: "USF Assistência", categoria: "USF", telefone: "(19) 3523-7882", horario: "—", icone: "🏥" },
      { id: "55", titulo: "USF Ferraz", categoria: "USF", telefone: "(19) 3538-1268", horario: "—", icone: "🏥" },
      { id: "56", titulo: "USF Ajapi", categoria: "USF", telefone: "(19) 3539-1255", horario: "—", icone: "🏥" },
      { id: "57", titulo: "USF Mãe Preta I/II", categoria: "USF", telefone: "(19) 3536-3396", horario: "—", icone: "🏥" },
      { id: "58", titulo: "USF Palmeiras I/II", categoria: "USF", telefone: "(19) 3524-2202", horario: "—", icone: "🏥" },
      { id: "59", titulo: "USF Jardim Novo I/II", categoria: "USF", telefone: "(19) 3534-4975", horario: "—", icone: "🏥" },
      { id: "60", titulo: "USF Benjamin de Castro", categoria: "USF", telefone: "(19) 3524-0313", horario: "—", icone: "🏥" },
      { id: "61", titulo: "USF Bonsucesso/Novo Wenzel", categoria: "USF", telefone: "(19) 3534-0509", horario: "—", icone: "🏥" },
      { id: "62", titulo: "USF Jardim das Flores", categoria: "USF", telefone: "(19) 3532-5783", horario: "—", icone: "🏥" },
      { id: "63", titulo: "USF Guanabara", categoria: "USF", telefone: "(19) 3532-6248", horario: "—", icone: "🏥" },
      { id: "64", titulo: "USF Panorama", categoria: "USF", telefone: "(19) 3532-5377", horario: "—", icone: "🏥" },
      { id: "65", titulo: "USF Terra Nova", categoria: "USF", telefone: "(19) 3524-2162", horario: "—", icone: "🏥" },
      { id: "66", titulo: "CRAS Mãe Preta/Jardim Bandeirantes", categoria: "Assistência social", telefone: "(19) 3524-9954", horario: "8h–17h", icone: "🤝" },
      { id: "67", titulo: "CRAS Jardim Brasília", categoria: "Assistência social", telefone: "(19) 3533-3752", horario: "8h–17h", icone: "🤝" },
      { id: "68", titulo: "CRAS Jardim Bom Retiro", categoria: "Assistência social", telefone: "(19) 3531-3243", horario: "8h–17h", icone: "🤝" },
      { id: "69", titulo: "CRAS Jardim Independência", categoria: "Assistência social", telefone: "(19) 3535-4558", horario: "8h–17h", icone: "🤝" },
      { id: "70", titulo: "CRAS Panorama", categoria: "Assistência social", telefone: "(19) 3523-5112", horario: "8h–17h", icone: "🤝" },
      { id: "71", titulo: "CRAS Terra Nova", categoria: "Assistência social", telefone: "(19) 3533-3556", horario: "8h–17h", icone: "🤝" },
      { id: "72", titulo: "Conselho Tutelar Sul", categoria: "Criança/adolescente", telefone: "(19) 3533-5411", horario: "Plantão", icone: "👶" },
      { id: "73", titulo: "Conselho Tutelar Norte", categoria: "Criança/adolescente", telefone: "(19) 99336-6682", horario: "Plantão", icone: "👶" },
      { id: "74", titulo: "INSS", categoria: "Previdência", telefone: "135", horario: "Seg–sáb", icone: "📄" },
      { id: "75", titulo: "Correios", categoria: "Encomendas", telefone: "3003-0100", horario: "—", icone: "📦" }
    ];

    return NextResponse.json({ success: true, telefones: telefonesUteis });
  } catch (error) {
    return NextResponse.json({ success: false, error: "Erro ao buscar telefones" }, { status: 500 });
  }
}