"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";

type CadastroANP = {
  codigoSIMP: string; autorizacao: string; distribuidora: string;
  produtos: Array<{ produto?: string }>; latitude: string; longitude: string;
  validacao: string; statusSIGAF: string;
};
type Preco = {
  revenda: string; cnpj: string; endereco: string; bairro: string; cep: string;
  produto: string; dataColeta: string; valor: number; bandeira: string; cadastroANP?: CadastroANP | null;
};
type Resposta = { sucesso: boolean; atualizadoEm: string | null; precos: Preco[]; aviso?: string; erro?: string };
type Localizacao = { lat:number; lng:number };
const abas=["GASOLINA","ETANOL","DIESEL S10","DIESEL","GLP"] as const;
const norm=(s:string)=>(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase();
function bate(produto:string,aba:string){const p=norm(produto);if(aba==="DIESEL")return p==="DIESEL"||p.includes("S500")||p.includes("S-500");if(aba==="DIESEL S10")return (p.includes("DIESEL")&&p.includes("S10"))||p.includes("S-10");if(aba==="GLP")return p.includes("GLP");return p.includes(aba);}
function num(v:string|undefined){const n=Number(String(v||"").replace(",","."));return Number.isFinite(n)&&n!==0?n:null;}
function rad(v:number){return v*Math.PI/180}
function dist(a:Localizacao,lat:number,lng:number){const R=6371,dLat=rad(lat-a.lat),dLng=rad(lng-a.lng);const x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(lat))*Math.sin(dLng/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}

export default function CombustiveisPage(){
 const[dados,setDados]=useState<Resposta|null>(null),[aba,setAba]=useState<string>("GASOLINA"),[busca,setBusca]=useState(""),[mapa,setMapa]=useState(false),[loc,setLoc]=useState<Localizacao|null>(null),[erroLoc,setErroLoc]=useState("");
 const mapaRef=useRef<HTMLDivElement|null>(null),mapaObj=useRef<any>(null),camada=useRef<any>(null),leaflet=useRef<any>(null),geoCache=useRef<Map<string,Localizacao|null>>(new Map());
 useEffect(()=>{fetch("/api/combustiveis").then(r=>r.json()).then(setDados).catch(()=>setDados({sucesso:false,atualizadoEm:null,precos:[],erro:"Não foi possível carregar os preços."}))},[]);
 const lista=useMemo(()=>{const q=norm(busca);return(dados?.precos||[]).filter(p=>bate(p.produto,aba)&&(!q||norm(p.revenda+" "+p.bairro+" "+p.bandeira).includes(q))).sort((a,b)=>a.valor-b.valor)},[dados,aba,busca]);
 function localizar(){if(!navigator.geolocation){setErroLoc("Localização não disponível.");return}setErroLoc("");navigator.geolocation.getCurrentPosition(p=>setLoc({lat:p.coords.latitude,lng:p.coords.longitude}),()=>setErroLoc("Localização não autorizada. O mapa continua disponível."),{enableHighAccuracy:true,timeout:10000,maximumAge:30000})}
 useEffect(()=>{if(!mapa||!mapaRef.current)return;let cancel=false;(async()=>{const obterCoord=async(p:Preco)=>{const lat=num(p.cadastroANP?.latitude),lng=num(p.cadastroANP?.longitude);if(lat!==null&&lng!==null)return{lat,lng};const chave=[p.endereco,p.bairro,"Rio Claro","SP","Brasil"].filter(Boolean).join(", ");if(geoCache.current.has(chave))return geoCache.current.get(chave)||null;try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=br&q=${encodeURIComponent(chave)}`,{headers:{"Accept-Language":"pt-BR"}});const j=await r.json();const g=Array.isArray(j)&&j[0]?{lat:Number(j[0].lat),lng:Number(j[0].lon)}:null;geoCache.current.set(chave,g);return g}catch{geoCache.current.set(chave,null);return null}};if(!leaflet.current){const L=await import("leaflet");if(cancel)return;leaflet.current=L;if(!document.getElementById("leaflet-comb-css")){const l=document.createElement("link");l.id="leaflet-comb-css";l.rel="stylesheet";l.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.appendChild(l)}}const L=leaflet.current;if(!mapaObj.current){mapaObj.current=L.map(mapaRef.current).setView([-22.41,-47.56],12);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap"}).addTo(mapaObj.current);camada.current=L.layerGroup().addTo(mapaObj.current)}camada.current.clearLayers();const lim:[number,number][]=[];const unicos=Array.from(new Map(lista.map(p=>[String(p.cnpj||p.revenda),p])).values());for(const p of unicos){if(cancel)return;const g=await obterCoord(p);if(!g)continue;const{lat,lng}=g;lim.push([lat,lng]);const valor="R$ "+p.valor.toFixed(3).replace(".",",");const icon=L.divIcon({className:"",html:`<div style="background:#047857;color:white;border:3px solid white;border-radius:15px;padding:5px;min-width:62px;text-align:center;box-shadow:0 2px 8px #0005;font-size:11px;font-weight:900">⛽<br>${valor}</div>`,iconSize:[66,46],iconAnchor:[33,23]});L.marker([lat,lng],{icon}).bindPopup(`<b>${p.revenda}</b><br>${p.produto}: <b>${valor}</b><br>Coleta: ${p.dataColeta}`).addTo(camada.current)};if(loc){lim.push([loc.lat,loc.lng]);const icon=L.divIcon({className:"",html:'<div style="background:#2563eb;color:white;border:3px solid white;border-radius:999px;width:38px;height:38px;display:flex;align-items:center;justify-content:center;box-shadow:0 2px 8px #0005">📍</div>',iconSize:[38,38],iconAnchor:[19,38]});L.marker([loc.lat,loc.lng],{icon}).bindPopup("<b>Você está aqui</b>").addTo(camada.current)}if(lim.length>=2)mapaObj.current.fitBounds(lim,{padding:[30,30],maxZoom:15});setTimeout(()=>mapaObj.current?.invalidateSize(),100)})().catch(()=>{});return()=>{cancel=true}},[mapa,lista,loc,aba]);
 return <div className="min-h-screen bg-slate-100 pb-24 text-slate-900"><header className="bg-gradient-to-r from-emerald-700 to-emerald-900 text-white shadow-md"><div className="mx-auto max-w-md px-4 py-4 text-center"><div className="text-3xl">⛽</div><h1 className="mt-1 text-xl font-black">Combustíveis em Rio Claro</h1><p className="mt-1 text-[11px] text-white/85">Preços pesquisados oficialmente pela ANP</p></div></header><main className="mx-auto max-w-md space-y-4 px-4 py-4">
 <div className="grid grid-cols-2 gap-2">{abas.map(x=><button key={x} onClick={()=>setAba(x)} className={`rounded-xl px-3 py-3 text-xs font-black ${aba===x?"bg-emerald-700 text-white shadow":"bg-white text-slate-700"}`}>{x==="ETANOL"?"🌱 Etanol":x==="GASOLINA"?"⛽ Gasolina":x==="GLP"?"🔥 Gás GLP":"🚚 "+x.replace("DIESEL ","Diesel ")}</button>)}</div>
 <input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="🔎 Buscar posto, bairro ou bandeira" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none"/>
 {dados?.atualizadoEm&&<div className="rounded-xl border border-blue-100 bg-blue-50 px-3 py-2 text-center text-[11px] font-bold text-blue-800">📅 Última pesquisa encontrada em Rio Claro: {dados.atualizadoEm} • Fonte: ANP</div>}
 <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between gap-2 p-3"><div><p className="text-sm font-black">🗺️ Mapa dos preços</p><p className="text-[10px] text-slate-500">Somente postos com preço pesquisado pela ANP.</p></div><button onClick={()=>setMapa(v=>!v)} className="rounded-xl bg-slate-900 px-3 py-2 text-[10px] font-black text-white">{mapa?"Fechar":"Abrir mapa"}</button></div>{mapa&&<><div className="px-3 pb-3"><button onClick={localizar} className="w-full rounded-xl bg-blue-600 px-3 py-2.5 text-xs font-black text-white">📍 Mostrar minha localização</button>{erroLoc&&<p className="mt-2 text-[10px] font-bold text-red-600">{erroLoc}</p>}</div><div ref={mapaRef} className="h-[390px] w-full bg-slate-100"/></>}</section>
 {!dados&&<div className="rounded-2xl bg-white p-8 text-center text-sm font-bold text-slate-500">Consultando a ANP...</div>}{dados&&!dados.sucesso&&<div className="rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">{dados.erro}</div>}{dados?.sucesso&&lista.length===0&&<div className="rounded-2xl bg-white p-6 text-center text-sm text-slate-500">Nenhum preço encontrado para este combustível na pesquisa mais recente.</div>}
 <div className="space-y-3">{lista.map((p,i)=>{const lat=num(p.cadastroANP?.latitude),lng=num(p.cadastroANP?.longitude),d=loc&&lat!==null&&lng!==null?dist(loc,lat,lng):null;return <article key={p.cnpj+p.produto+i} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0">{i===0&&<span className="mb-1 inline-block rounded-full bg-amber-100 px-2 py-1 text-[9px] font-black text-amber-800">🏆 MENOR PREÇO PESQUISADO</span>}<h2 className="text-sm font-black">{p.revenda}</h2><p className="text-[10px] font-bold text-slate-500">{p.cadastroANP?.distribuidora||p.bandeira}</p></div><div className="shrink-0 text-right"><p className="text-[9px] font-black uppercase text-slate-400">{p.produto}</p><p className="text-2xl font-black text-emerald-700">R$ {p.valor.toFixed(3).replace(".",",")}</p><p className="text-[9px] text-slate-400">{aba==="GLP"?"por recipiente":"por litro"}</p></div></div><div className="mt-3 border-t border-slate-100 pt-3 text-[11px] leading-5 text-slate-600"><p>📍 {p.endereco}{p.bairro?" • "+p.bairro:""}</p><p>🗓️ Coleta: {p.dataColeta}</p>{d!==null&&<p className="font-black text-blue-700">📍 {d<1?Math.round(d*1000)+" m":d.toFixed(1).replace(".",",")+" km"} de você</p>}</div><a href={lat!==null&&lng!==null?`https://www.google.com/maps/search/?api=1&query=${lat},${lng}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.endereco+", Rio Claro, SP")}`} target="_blank" rel="noreferrer" className="mt-3 block rounded-xl bg-slate-100 px-3 py-2 text-center text-xs font-black text-slate-700">📍 Como chegar</a></article>})}</div>
 <div className="rounded-2xl border border-amber-200 bg-amber-50 p-3 text-[10px] leading-4 text-amber-900"><b>Importante:</b> mostramos apenas postos que aparecem no levantamento de preços da ANP nesta coleta. Os valores não são em tempo real.</div><Link href="/utilidades" className="block text-center text-xs font-black text-blue-800">← Voltar para Utilidades</Link>
 </main></div>
}